config/routes.rb
Rails.application.routes.draw do
  # Get  /About
  get "about" ,to:"about#index"

  get "sign_up",to: "registrations#new"
  post "sign_up",to: "registrations#create"

  get "sign_in",to: "session#new"
  post "sign_in",to: "session#create"

  delete "logout",to: "session#destroy"
  root to: "main#index"

  get 'test' => 'session#test'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business.rb
class Business < ApplicationRecord
end

app/models/current.rb
class Current<ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
  # self.table_name="teachers"
end

app/models/teacher.rb
class Teacher < ApplicationRecord

end

app/models/user.rb
#eamail:string
# password_digest:string
# password: string virtual
# password_confirmation:string virtual

class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true,format: {with: /\A[^@\s]+@[^@\s]+\z/,message: "must be a valid email address"}
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :danger, :info, :warning
  before_action :set_current_user

  def set_current_user
    if session[:user_id]
    Current.user=User.find_by(id: session[:user_id])
  end

  end
end

app/controllers/business_controller.rb
class BusinessController < ApplicationController

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    #flash[:notice]  = "Logged in Succesfully"



  end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController


end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user= User.new
  end


  def create
    @user=User.new(user_params)
    if @user.save
      session[:user_id]=@user.id
      redirect_to root_path, notice: "Successfully created account "
    else
      flash[:alert] = "Something was wrong"
      render :new
    end

    #render plain: params[:user]
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end


end

app/controllers/session_controller.rb
class SessionController<ApplicationController

  def new

  end

  def create
    user =User.find_by(email:params[:email])
    if user.present? && user.authenticate(params[:password])
      session[:user_id]=user.id
      redirect_to root_path,notice: "Logged In Succesfully"
      # flash[:info] = "Logged In Succesfully"
    else
      #flash is working but how
      flash[:alert] = "Invalid email or password"
      render :new
      # redirect_to sign_in_path
    end
  end

  def destroy
    session[:user_id]=nil
    redirect_to root_path,notice: "logged out"
  end

  def test
    @a=Teacher.last
    render json: @a.attributes.slice('name', :'fname')
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/business_helper.rb
module BusinessHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/about/index.html.erb
<h1>About Us</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlaOwnedg</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render partial: "shared/navbar" %>


  <div class="container">
    <%= render partial: "shared/flash" %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center">
<h1>Welcome to BlaOwned</h1>

</div>

app/views/session/new.html.erb
<h1>Sign In</h1>

<%= form_with url: sign_in_path do |form|%>

  <% flash.each do |type, msg| %>
    <div class="alert alert-danger">
      <%= msg %>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :email %>
    <%= form.text_field :email,class: "form-control",placeholder: "steve@apple.com" %>
  </div>

  <div class="mb-3">
    <%= form.label :password %>
    <%= form.password_field :password,class: "form-control",placeholder: "password"  %>
  </div>

  <div class="mb-3">
    <%=form.submit "Sign In",class: "btn btn-primary"%>
  </div>



<% end %>

app/views/session/test.html.erb
=======================================

app/views/shared/_flash.html.erb
<%= flash[:notice] %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "BlaOwned", root_path,class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
        <%= link_to "New", root_path,class: "nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "About",about_path,class: "nav-link" %>
        </li>
      </ul>


      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if Current.user %>
          <li class="nav-item">
          <span class="navbar-text"><%=Current.user.email %></span>
          </li>
          <li class="nav-item">
        <%= button_to "Logout", logout_path, method: :delete,class: "btn btn-outline-secondary" %>
          </li>
        <% else %>
          <li class="nav-item">
          <%= link_to "Login",sign_in_path,class: "nav-link" %>
          </li>
          <li class="nav-item">
          <%= link_to "Sign Up",sign_up_path,class: "nav-link" %>
          </li>
          <%end %>
      </ul>
    </div>
  </div>
</nav>